const mongoose = require("mongoose");
const Listing = require("../models/Listing");
const store = require("../devStore");
const usingDatabase = () => mongoose.connection.readyState === 1;
const calculateDistance = (lat1, lon1, lat2, lon2) => { const p = Math.PI / 180; const a = .5-Math.cos((lat2-lat1)*p)/2+Math.cos(lat1*p)*Math.cos(lat2*p)*(1-Math.cos((lon2-lon1)*p))/2; return 12742*Math.asin(Math.sqrt(a)); };
exports.getListings = async (req,res) => { try { const {lat,lng,radius,type}=req.query; let listings=usingDatabase()?await Listing.find(type&&type!=="all"?{type}:{}).populate("author","username email phone").sort({createdAt:-1}).lean():store.getListings().filter(item=>!type||type==="all"||item.type===type); if(lat&&lng&&radius) listings=listings.map(item=>({...item,distance:calculateDistance(+lat,+lng,item.location.lat,item.location.lng)})).filter(item=>item.distance<=+radius); res.json(listings); } catch(error){console.error("Listing fetch error:",error.message);res.status(500).json({error:"Failed to fetch listings"});} };
exports.createListing = async (req,res) => { try { const fields={...req.body,author:req.user.id}; const listing=usingDatabase()?await new Listing(fields).save():store.createListing(fields);res.status(201).json(listing); } catch(error){console.error("Listing create error:",error.message);res.status(500).json({error:"Failed to create listing"});} };
exports.getMyListings = async (req,res) => { try { const listings=usingDatabase()?await Listing.find({author:req.user.id}).sort({createdAt:-1}):store.getUserListings(req.user.id);res.json(listings); } catch {res.status(500).json({error:"Failed to fetch user listings"});} };
exports.deleteListing = async (req,res) => { try { if(!usingDatabase()){const result=store.deleteListing(req.params.id,req.user.id);if(result==="missing")return res.status(404).json({error:"Listing not found"});if(result==="forbidden")return res.status(403).json({error:"Unauthorized to delete this listing"});return res.json({message:"Listing deleted"});} const listing=await Listing.findById(req.params.id);if(!listing)return res.status(404).json({error:"Listing not found"});if(listing.author.toString()!==req.user.id)return res.status(403).json({error:"Unauthorized to delete this listing"});await listing.deleteOne();res.json({message:"Listing deleted"}); } catch {res.status(500).json({error:"Failed to delete listing"});} };
